/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pesanan;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


public class database_order extends javax.swing.JFrame {
NumberFormat nf = NumberFormat.getNumberInstance(new Locale ("in", "ID"));

private void kosongkanform(){
    txtnama.setEditable(true);
    txtnama.setText(null);
    txttelepon.setText(null);
    CBjeniscucian.setSelectedItem(this);
    txtharga.setText(null);
    txtberat.setText(null);
    CBpaketantrian.setSelectedItem(this);
    txthargapaket.setText(null);
    txttotalharga.setText(null);
    }


private void tampilkandata(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. Faktur");
        model.addColumn("NAMA");
        model.addColumn("NO TLP");
        model.addColumn("JENIS PESANAN");
        model.addColumn("HARGA / PAKET");
        model.addColumn("JUMLAH");
        model.addColumn("H x P ");
        model.addColumn("PAKET ANTAR");
        model.addColumn("HARGA PAKET ");
        model.addColumn("TOTAL HARGA");
        try {
            
            String sql = "SELECT * FROM db_form_order";
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10)});
                
            }
            tabelorder.setModel(model); //masukin nama tabel
            
        }catch(SQLException e){
            System.out.println("Error" + e.getMessage());
        }
        int b = tabelorder.getRowCount();
        txtall.setText(""+b);
        try {
            String sum;
            //String sql = "SELECT FORMAT(SUM(total_harga_costumer),3) as fullorder FROM db_form_order ";
            String sql = "SELECT SUM(total_harga_costumer) as fullorder FROM db_form_order ";
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement prep = conn.prepareStatement(sql);
            java.sql.ResultSet res = prep.executeQuery();
            res.next();
            sum = res.getString(1);
    
            System.out.println("BERHASIL");
            txtallorder.setText(""+sum);
        }catch(SQLException e){
            System.out.println("Error" + e.getMessage());
        }
    }
private void nofaktur(){
        try {
     
    
            String sql="SELECT MAX(RIGHT(no_faktur,4)) AS nofaktur FROM db_form_order ";
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            if (res.next()) {
                String no_auto,nol;
                int p;
                no_auto = (Integer.toString(res.getInt(1)+1));
                p = no_auto.length();
                nol = "";
                for (int i=1;i<=4-p;i++) {
                nol = nol + "0";
                }
               txtnofaktur.setText("B"+nol+no_auto);
            }
           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
     
    }


    /**
     * Creates new form database_order
     */
    public database_order() {
        initComponents();
        icon();
        nofaktur();
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txttotalharga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnhitung = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        txthargapaket = new javax.swing.JTextField();
        CBpaketantrian = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtberat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CBjeniscucian = new javax.swing.JComboBox<>();
        txttelepon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtallorder = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        txtberatxharga = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        txtnofaktur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DATA PESANAN -  ADMIN MENU");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("DATABASE COSTUMER");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("DAFTAR PESANAN");

        txtharga.setEditable(false);
        txtharga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txttotalharga.setEditable(false);
        txttotalharga.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        txttotalharga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotalharga.setText("0");
        txttotalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalhargaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setText("total harga");

        btnhitung.setText("HITUNG");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        txthargapaket.setEditable(false);
        txthargapaket.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txthargapaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargapaketActionPerformed(evt);
            }
        });

        CBpaketantrian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH ---", "REGULER", "INSTANT", "HOLIDAY", " " }));
        CBpaketantrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBpaketantrianActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setText("PAKET ANTAR");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("JUMLAH");

        txtberat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtberatActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setText("HARGA ");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("JENIS MAKANAN");

        CBjeniscucian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH ---", "PAKET 1", "PAKET 2", "PAKET 3", "PAKET 4", "PAKET 5" }));
        CBjeniscucian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBjeniscucianActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("NO. HANDPHONE");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("NAMA");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabelorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tabelorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelorderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelorder);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 0, 51));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btnrefresh.setBackground(new java.awt.Color(51, 204, 255));
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("↻ REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        btnkembali.setBackground(new java.awt.Color(255, 0, 0));
        btnkembali.setForeground(new java.awt.Color(255, 255, 255));
        btnkembali.setText("KEMBALI ➥");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        jLabel3.setText("TOTAL SELURUH PESANAN");

        txtall.setEditable(false);
        txtall.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtallActionPerformed(evt);
            }
        });

        txtallorder.setEditable(false);
        txtallorder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Print Semua Laporan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_hapus)
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(txtall, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2)
                    .addComponent(txtallorder, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnrefresh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnkembali, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtallorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 61, Short.MAX_VALUE))
        );

        txtberatxharga.setEditable(false);
        txtberatxharga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtnofaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(116, 116, 116)
                                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txttelepon)
                                            .addComponent(CBjeniscucian, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtharga)
                                            .addComponent(txtberat)
                                            .addComponent(CBpaketantrian, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtberatxharga, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(txthargapaket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtnofaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CBjeniscucian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtberat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtberatxharga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CBpaketantrian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txthargapaket, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(txttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel11)
                        .addGap(14, 14, 14)))
                .addGap(11, 11, 11)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1226, 732));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttotalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalhargaActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        if(txtnama.getText().isEmpty() || txttelepon.getText().isEmpty() || CBjeniscucian.getSelectedIndex()==0 || txtharga.getText().isEmpty() || txtberat.getText().isEmpty() || txtberatxharga.getText().isEmpty() || CBpaketantrian.getSelectedIndex()==0 || txthargapaket.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ISI SEMUA KOLOM");
    }else{
        int     hslharga = Integer.parseInt(txtharga.getText().replace(".","")),
                hslberat = Integer.parseInt(txtberat.getText().replace(".","")),
                hb = hslberat*hslharga,
                hslantrian =  Integer.parseInt(txthargapaket.getText().replace(".","")),
                totalprice;
                totalprice = (hslharga*hslberat)+hslantrian;
                txttotalharga.setText(nf.format(totalprice)); 
                
        }
        
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtnofaktur.setText(null);
        kosongkanform();
        tampilkandata();
        nofaktur();

    }//GEN-LAST:event_btnresetActionPerformed

    private void txthargapaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargapaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargapaketActionPerformed

    private void CBpaketantrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBpaketantrianActionPerformed
        // TODO add your handling code here:
        if(CBjeniscucian.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Pilih Jenis Cucian Terlebih Dahulu");
            txthargapaket.setText(nf.format(0));
        } else if(txtberat.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Berat Tidak Boleh Kosong!");
            txthargapaket.setText(nf.format(0));
        }else{
            switch (CBpaketantrian.getSelectedIndex()){
            case 0:
                   txthargapaket.setText("");
                    break;
            case 1:
                   txthargapaket.setText(nf.format(0));
                    break;
            case 2:
                   txthargapaket.setText(nf.format(5000));
                    break;
            case 3:
                   txthargapaket.setText(nf.format(15000));
                    break;
            default:
                    txthargapaket.setText("");
                    break; 
            }
        }
       
        int    hslharga = Integer.parseInt(txtharga.getText().replace(".","")),
                hslberat = Integer.parseInt(txtberat.getText().replace(".","")),
                hb = hslberat*hslharga;
                txtberatxharga.setText(nf.format(hb));
    }//GEN-LAST:event_CBpaketantrianActionPerformed

    private void txtberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberatActionPerformed

    private void CBjeniscucianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBjeniscucianActionPerformed
        // TODO add your handling code here:
           if(txtnama.getText().isEmpty() || txttelepon.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama / No. Handphone Tidak Boleh Kosong");
            txthargapaket.setText(nf.format(0));
        }else{
        switch (CBjeniscucian.getSelectedIndex()){
            case 0:
                txtharga.setText(nf.format(0));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                
                break;
            case 1:
                
                txtharga.setText(nf.format(5000));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                
                break;
            case 2:
                txtharga.setText(nf.format(25000));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                break;
            case 3:
                txtharga.setText(nf.format(15000));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                break;
            case 4:
                txtharga.setText(nf.format(5000));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                break;
            case 5:
                txtharga.setText(nf.format(25000));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                break;
        }
           }
    }//GEN-LAST:event_CBjeniscucianActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE db_form_order SET nama='"+txtnama.getText()+"',no_tlp='"+txttelepon.getText()+"',jenis_cucian='"+CBjeniscucian.getSelectedItem()+"',harga_cucian='"+txtharga.getText()+"',berat_cucian='"+txtberat.getText()+"',harga_berat='"+txtberatxharga.getText()+"',paket_antrian='"+CBpaketantrian.getSelectedItem()+"',harga_paket_antrian='"+txthargapaket.getText()+"',total_harga_costumer='"+txttotalharga.getText()+"'WHERE nama= '"+txtnama.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Edit Data Berhasil");
        }catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        txtnofaktur.setText(null);
        tampilkandata();
        kosongkanform();
        nofaktur();
    }//GEN-LAST:event_btn_editActionPerformed

    private void tabelorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelorderMouseClicked
        // TODO add your handling code here:
        int baris = tabelorder.rowAtPoint(evt.getPoint());
        String no_faktur = tabelorder.getValueAt(baris, 0).toString();
        txtnofaktur.setText(no_faktur);
        String nama = tabelorder.getValueAt(baris, 1).toString();
        txtnama.setText(nama);
        String no_tlp = tabelorder.getValueAt(baris, 2).toString();
        txttelepon.setText(no_tlp);
        String jenis_cucian = tabelorder.getValueAt(baris, 3).toString();
        CBjeniscucian.setSelectedItem(jenis_cucian);
        String harga_cucian = tabelorder.getValueAt(baris, 4).toString();
        txtharga.setText(harga_cucian);
        String berat_cucian = tabelorder.getValueAt(baris, 5).toString();
        txtberat.setText(berat_cucian);
        String harga_berat = tabelorder.getValueAt(baris, 6).toString();
        txtberatxharga.setText(harga_berat);
        String paket_antrian = tabelorder.getValueAt(baris, 7).toString();
        CBpaketantrian.setSelectedItem(paket_antrian);
        String harga_paket = tabelorder.getValueAt(baris, 8).toString();
        txthargapaket.setText(harga_paket);
        String total_harga_costumer = tabelorder.getValueAt(baris, 9).toString();
        txttotalharga.setText(total_harga_costumer);
    }//GEN-LAST:event_tabelorderMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        if(txtnama.getText().isEmpty() || txttelepon.getText().isEmpty() || CBjeniscucian.getSelectedIndex()==0 || txtharga.getText().isEmpty() || txtberat.getText().isEmpty() || txtberatxharga.getText().isEmpty() || CBpaketantrian.getSelectedIndex()==0 || txthargapaket.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"SEMUA KOLOM WAJIB DIISI");
        }else{
        try{
            String sql = "DELETE FROM db_form_order WHERE no_faktur= '"+txtnofaktur.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Hapus Data Berhasil");
        }catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        txtnofaktur.setText(null);
        tampilkandata();
        kosongkanform();
        nofaktur();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:    
        if(txtnama.getText().isEmpty() || txttelepon.getText().isEmpty() || CBjeniscucian.getSelectedIndex()==0 || txtharga.getText().isEmpty() || txtberat.getText().isEmpty() || txtberatxharga.getText().isEmpty() || CBpaketantrian.getSelectedIndex()==0 || txthargapaket.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"SEMUA KOLOM WAJIB DIISI");
        }else if(txttotalharga.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "SILAHKAN KLIK HITUNG TERLEBIH DAHULU");
        }else{
        try {
            String sql = "INSERT INTO db_form_order VALUES ('"+txtnofaktur.getText()+"','"+txtnama.getText()+"','"+txttelepon.getText()+"','"+CBjeniscucian.getSelectedItem()+"','"+txtharga.getText().replace(".","")+"','"+txtberat.getText()+"','"+txtberatxharga.getText().replace(".","")+"','"+CBpaketantrian.getSelectedItem()+"','"+txthargapaket.getText().replace(".","")+"','"+txttotalharga.getText().replace(".","")+"')";
            
            java.sql.Connection conn = (Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Proses Simpan Data Berhasil");
            txtnofaktur.setText(null);
            tampilkandata();
            kosongkanform();
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        txtnofaktur.setText(null);
        kosongkanform();
        tampilkandata();
        nofaktur();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        menu_admin menu_admin = new menu_admin();
        menu_admin.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void txtallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtallActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
    String report = "C:\\Users\\Windows 10\\OneDrive\\Documents\\NetBeansProjects\\catering\\src\\Pesanan\\DataOrder.jrxml";
    
    HashMap<String, Object> hash = new HashMap<>();
    // Mengambil parameter dari ireport
    hash.put("paradodos", txtcari.getText());
    
    JasperReport JRpt = JasperCompileManager.compileReport(report);
    JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, koneksi.getKoneksi());
    JasperViewer.viewReport(JPrint, false);
    } catch (JRException rptexcpt) {
    System.out.println("Report Can't view because: " + rptexcpt);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JasperReport reports;
String path =".\\src\\Pesanan\\FullDataOrder.jasper";
try {
reports = (JasperReport) JRLoader.loadObjectFromFile(path);
JasperPrint jprint = JasperFillManager.fillReport(path,null,koneksi.getKoneksi());
JasperViewer jviewer = new JasperViewer(jprint,false);
jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
jviewer.setVisible(true);
}catch (Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
         
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(database_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(database_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(database_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(database_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new database_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBjeniscucian;
    private javax.swing.JComboBox<String> CBpaketantrian;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JTable tabelorder = new javax.swing.JTable();
    public static final javax.swing.JTextField txtall = new javax.swing.JTextField();
    private javax.swing.JTextField txtallorder;
    private javax.swing.JTextField txtberat;
    private javax.swing.JTextField txtberatxharga;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txthargapaket;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnofaktur;
    private javax.swing.JTextField txttelepon;
    private javax.swing.JTextField txttotalharga;
    // End of variables declaration//GEN-END:variables

    private void icon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
}

   
}