/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pesanan;


import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;




public class form_order extends javax.swing.JFrame {
    private void nofaktur(){
        try {
     
    
            String sql="SELECT MAX(RIGHT(no_faktur,4)) AS nofaktur FROM db_form_order ";
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            if (res.next()) {
                String no_auto,nol;
                int p;
                no_auto = (Integer.toString(res.getInt(1)+1));
                p = no_auto.length();
                nol = "";
                for (int i=1;i<=4-p;i++) {
                nol = nol + "0";
                }
               txtnofaktur.setText("B"+nol+no_auto);
            }
           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
     
    }

   
private void kosongkanform(){
    
    CBjeniscucian.setSelectedItem(this);
    txtharga.setText(null);
    txtberat.setText(null);
    txtberatxharga.setText(null);
    CBpaketantrian.setSelectedItem(this);
    txthargapaket.setText(null);
    txttotalharga.setText(null);
    
    
   
    }

private void tampilkantable(){   
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
Object obj [] = new Object[6];
obj [1] = CBjeniscucian.getSelectedItem();
obj [2] = txtharga.getText();
obj [3] = txtberat.getText();
obj [4] = CBpaketantrian.getSelectedItem();
obj [5] = txttotalharga.getText();

model.addRow(obj);
int baris = model.getRowCount();
for (int a=0; a< baris; a++){
    String no = String.valueOf(a+1);
    model.setValueAt(no + ".",a,0);
}

jTable1.setRowHeight(30);

jmltotalharga();

}     
NumberFormat nf = NumberFormat.getNumberInstance(new Locale ("in", "ID"));
    public form_order() {
        initComponents();
        kosongkanform();
        icon();
        nofaktur();
        
  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namamu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttotalharga = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        CBjeniscucian = new javax.swing.JComboBox<>();
        txtharga = new javax.swing.JTextField();
        txtberat = new javax.swing.JTextField();
        CBpaketantrian = new javax.swing.JComboBox<>();
        txthargapaket = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        txtberatxharga = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnbayar = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnreset1 = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtplustable = new javax.swing.JTextField();
        txtnofaktur = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU ORDER");

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));
        jPanel1.setForeground(new java.awt.Color(204, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jLabel1.setText("KELUAR");
        jLabel1.setPreferredSize(new java.awt.Dimension(98, 52));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jLabel2.setText("SELAMAT DATANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namamu, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(527, 527, 527)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(namamu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("NAMA");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("NO. HANDPHONE");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("JENIS MAKANAN");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("JUMLAH");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setText("HARGA ");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setText("PAKET ANTAR");

        txttotalharga.setEditable(false);
        txttotalharga.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        txttotalharga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotalharga.setText("0");

        txttelepon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtteleponMouseClicked(evt);
            }
        });

        CBjeniscucian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH ---", "PAKET 1", "PAKET 2", "PAKET 3", "PAKET 4", "PAKET 5" }));
        CBjeniscucian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBjeniscucianActionPerformed(evt);
            }
        });

        txtharga.setEditable(false);

        txtberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtberatActionPerformed(evt);
            }
        });

        CBpaketantrian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH ---", "REGULER", "INSTANT", "HOLIDAY" }));
        CBpaketantrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBpaketantrianActionPerformed(evt);
            }
        });

        txthargapaket.setEditable(false);
        txthargapaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargapaketActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setText("Total Harga");

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });

        txtkembalian.setEditable(false);

        btnhitung.setText("HITUNG");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        txtberatxharga.setEditable(false);

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setText("TOTAL HARGA");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setText("TOTAL BAYAR");

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setText("KEMBALIAN");

        btnbayar.setText("BAYAR");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnreset1.setText("RESET");
        btnreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset1ActionPerformed(evt);
            }
        });

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Jenis Pesanan", "Harga /Paket", "Jumlah", "Paket Antar", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtplustable.setEditable(false);
        txtplustable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplustableActionPerformed(evt);
            }
        });

        txtnofaktur.setEditable(false);
        txtnofaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnofakturActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setText("NO. FAKTUR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtberatxharga)
                                .addComponent(txttelepon)
                                .addComponent(CBjeniscucian, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtharga)
                                .addComponent(txtberat)
                                .addComponent(CBpaketantrian, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel15))
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(txtnofaktur)))
                        .addComponent(txthargapaket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(543, 543, 543)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtbayar)
                                    .addComponent(txtplustable, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnreset1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1498, 1498, 1498))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1432, 1432, 1432))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtnofaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(CBjeniscucian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtberat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(txtberatxharga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(CBpaketantrian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txthargapaket, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel11))
                                    .addComponent(txttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtplustable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(btnbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(btnreset1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(229, 229, 229))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CBjeniscucianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBjeniscucianActionPerformed
        // TODO add your handling code here:
        if(txtnama.getText().isEmpty() || txttelepon.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama / No. Handphone Tidak Boleh Kosong");
            txthargapaket.setText(nf.format(0));
        }else{
        switch (CBjeniscucian.getSelectedIndex()){
            case 0:
                txtharga.setText(nf.format(0));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                
                break;
            case 1:
                
                txtharga.setText(nf.format(5000));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                
                break;
            case 2:
                txtharga.setText(nf.format(25000));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                break;
            case 3:
                txtharga.setText(nf.format(15000));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                break;
            case 4:
                txtharga.setText(nf.format(30000));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                break;
            case 5:
                txtharga.setText(nf.format(25000));
                txtberat.setText("");
                CBpaketantrian.setSelectedItem(this);
                txthargapaket.setText("");
                txttotalharga.setText("");
                break;
        }
        }
    }//GEN-LAST:event_CBjeniscucianActionPerformed

    private void txthargapaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargapaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargapaketActionPerformed

    private void CBpaketantrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBpaketantrianActionPerformed
        // TODO add your handling code here:
        if(CBjeniscucian.getSelectedIndex() == 0){
    JOptionPane.showMessageDialog(null, "Pilih Jenis Cucian Terlebih Dahulu");
    txthargapaket.setText(nf.format(0));
    } else if(txtberat.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Berat Tidak Boleh Kosong!");
    txthargapaket.setText(nf.format(0));
    } else {
    switch (CBpaketantrian.getSelectedIndex()){
        case 0:
            txthargapaket.setText("");
            break;
        case 1:
            txthargapaket.setText(nf.format(0));
            break;
        case 2:
            txthargapaket.setText(nf.format(5000));
            break;
        case 3:
            txthargapaket.setText(nf.format(15000));
            break;
        default:
            txthargapaket.setText("");
            break; 
    }

    try {
        int hslharga = Integer.parseInt(txtharga.getText().replace(".",""));
        int hslberat = Integer.parseInt(txtberat.getText().replace(".",""));
        int hb = hslberat * hslharga;
        txtberatxharga.setText(nf.format(hb));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Masukkan angka yang valid untuk harga dan berat.");
    }
}               
    }//GEN-LAST:event_CBpaketantrianActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        if(txtnama.getText().isEmpty() || txttelepon.getText().isEmpty() || CBjeniscucian.getSelectedIndex()==0 || txtharga.getText().isEmpty() || txtberat.getText().isEmpty() || txtberatxharga.getText().isEmpty() || CBpaketantrian.getSelectedIndex()==0 || txthargapaket.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ISI SEMUA KOLOM");
    }else{
        int     hslharga = Integer.parseInt(txtharga.getText().replace(".","")),
                hslberat = Integer.parseInt(txtberat.getText().replace(".","")),
                hb = hslberat*hslharga,
                hslantrian =  Integer.parseInt(txthargapaket.getText().replace(".","")),
                totalprice;
                totalprice = (hslharga*hslberat)+hslantrian;
                txttotalharga.setText(nf.format(totalprice)); 
                
        }
    }//GEN-LAST:event_btnhitungActionPerformed

    private void txtberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtberatActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Ingin Keluar?", 
                    "Keluar", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
            
            kosongkanform();
            
            form_login form_login= new  form_login();
            form_login.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        // TODO add your handling code here:
        if (txtplustable.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Total Harga Masih Kosong");
        } else if (txtbayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukan Jumlah Bayar");
        }else{
        int  ttl = Integer.parseInt(txtplustable.getText().replace(".", "")),
            byr = Integer.parseInt(txtbayar.getText().replace(".", "")),
            km = byr-ttl;
        if(byr<ttl ){
            JOptionPane.showMessageDialog(null, "Nominal Pembayaran Kurang");
        }else{
            txtkembalian.setText("Rp."+" "+nf.format(km));
            try {

                String report = ("C:\\Users\\Windows 10\\OneDrive\\Documents\\NetBeansProjects\\catering\\src\\Pesanan\\DataOrder.jrxml");
                
                 HashMap hash = new HashMap();
                //Mengambil parameter dari ireport
                hash.put("paradodos", txtnofaktur.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, koneksi.getKoneksi());
                JasperViewer.viewReport(JPrint, false);
            } catch (Exception rptexcpt) {
                System.out.println("Report Can't view because : " + rptexcpt);
            }
        }}
    }//GEN-LAST:event_btnbayarActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        kosongkanform();
        
       
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset1ActionPerformed
        // TODO add your handling code here:
        kosongkanform();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        txtplustable.setText("");
    }//GEN-LAST:event_btnreset1ActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if(txtnama.getText().isEmpty() || txttelepon.getText().isEmpty() || CBjeniscucian.getSelectedIndex()==0 || txtharga.getText().isEmpty() || txtberat.getText().isEmpty() || txtberatxharga.getText().isEmpty() || CBpaketantrian.getSelectedIndex()==0 || txthargapaket.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"SEMUA KOLOM WAJIB DIISI");
        }else if(txttotalharga.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "SILAHKAN KLIK HITUNG TERLEBIH DAHULU");
        }else{
        try {
            String sql = "INSERT INTO db_form_order VALUES ('"+txtnofaktur.getText()+"','"+txtnama.getText()+"','"+txttelepon.getText()+"','"+CBjeniscucian.getSelectedItem()+"','"+txtharga.getText().replace(".","")+"','"+txtberat.getText()+"','"+txtberatxharga.getText().replace(".","")+"','"+CBpaketantrian.getSelectedItem()+"','"+txthargapaket.getText().replace(".","")+"','"+txttotalharga.getText().replace(".","")+"')";
            
            java.sql.Connection conn = (Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Proses Simpan Data Berhasil");
            tampilkantable();
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txtteleponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtteleponMouseClicked
        // TODO add your handling code here:
         String hb =  (txtnama.getText());
         String h3 = hb.toUpperCase();
         namamu.setText(", "+h3);
    }//GEN-LAST:event_txtteleponMouseClicked

    private void txtplustableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplustableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplustableActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtnofakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnofakturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnofakturActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBjeniscucian;
    private javax.swing.JComboBox<String> CBpaketantrian;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnreset1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel namamu;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtberat;
    private javax.swing.JTextField txtberatxharga;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txthargapaket;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnofaktur;
    private javax.swing.JTextField txtplustable;
    private javax.swing.JTextField txttelepon;
    private javax.swing.JTextField txttotalharga;
    // End of variables declaration//GEN-END:variables

    private void jmltotalharga() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        int subtotal = 0;
        for(int a = 0; a < jTable1.getRowCount(); a++){
            subtotal += Integer.parseInt((String) 
                    jTable1.getValueAt(a, 5).toString().replace(".", ""));
        }
        txtplustable.setText(nf.format(subtotal));
    }

    private void icon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
}

}
